kind: ConfigMap
apiVersion: v1
metadata:
  name: api-id
  namespace: mossp
  labels:
    app.kubernetes.io/name: api-id
    spring.cloud.kubernetes.config: "true"
data:
  application.yaml: |-
    server:
      port: 8080
      name: api-id
    
    app:
      server-url: https://dev-apiid.mossp.co.kr

    external:
      api:
        base-url: https://dev-apispass.mossp.co.kr

    spring:
      application:
        name: api-id
      datasource:
        url: jdbc:mysql://db-2vtm31-kr1.vpc-cdb.gov-ntruss.com:3306/db_a_sc?useUnicode=true&serverTimezone=Asia/Seoul
        username: mossp_api
        password: mega!202501
        driver-class-name: com.mysql.cj.jdbc.Driver

    springdoc:
      swagger-ui:
        path: /swagger-ui
        
    # spring:
    #   application:
    #     name: "mossp"
    #   web:
    #     locale: ko_KR #locale 설정 - 메시지 관련
    #     locale-resolver: fixed #locale 고정
    #   config:
    #     activate:
    #       on-profile: dev
    #     use-legacy-processing: true
    #   mvc:
    #     pathmatch:
    #       matching-strategy: ant_path_matcher
    #   output:
    #     ansi:
    #       enabled: ALWAYS
    #   redis:
    #     host: 127.0.0.1
    #     port: 6379
    #     username:
    #     password:
    #     lettuce:
    #       pool:
    #         max-active: 20 # 최대 연결 수 default 10
    #         max-idle: 10 # 최대 유휴 연결 수 default 5
    #         min-idle: 1 # 최소 유휴 연결 수 default 1
    #         time-between-eviction-runs: 1000ms # 유휴 연결 테스트 주기
    #     timeout: 5000ms # 타임아웃 설정
    #   # (확인필요) feign + circuitbreaker
    #   # https://seongwon.dev/MSA/20230428-Resilience4J%EB%A1%9C_SpringBoot%EC%97%90%EC%84%9C_CircuitBreaker_%EC%82%AC%EC%9A%A9%ED%95%B4%EB%B3%B4%EA%B8%B0/
    #   cloud:
    #     openfeign:
    #       circuitbreaker:
    #         enabled: true
    # ---
    # Globals:
    #   LocalIp: 127.0.0.1
    #   DbType: mysql
    #   pageUnit: 10
    #   pageSize: 10
    #   posblAtchFileSize: 5242880
    #   fileStorePath: ./files
    #   addedOptions: false
    #   mysql:
    #     DriverClassName: com.mysql.cj.jdbc.Driver
    #     Url: jdbc:mysql://db-2vtm31-kr1.vpc-cdb.gov-ntruss.com:3306/db_m_mb?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    #     UserName: mossp_api
    #     Password: mega!202501

    #     ReadUrl: jdbc:mysql://db-2vtm31-kr1.vpc-cdb.gov-ntruss.com:3306/db_m_mb?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
        
    #     MaxConnectionPool: 1
    #     Url2: jdbc:mysql://db-2vtm31-kr1.vpc-cdb.gov-ntruss.com:3306/db_m_mb?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    #     UserName2: mossp_api
    #     Password2: mega!202501

    #   fileUpload:
    #     Extensions: .gif.jpg.jpeg.png.xls.xlsx.zip
    #   Allow:
    #     Origin: http://localhost:3000
    #   crypto:
    #     masterKey: 0123456789abcdef
    #     algoritm: smdc
    #     algorithmKeyHash: 6GiJ1kv+1lKVVJCdQhwk1WqlRhLhrMw+9W0BJII+GwE=
    #   jwt:
    #     secret: "eW91ci0yNTYtYml0LXNlY3JldA==" #base64 encoding : your-256-bit-secret
    #     expiration_time: 3600 #3600초 =  1시간
    #     refresh_time: 86400 # 86400초 = 24시간

    # server:
    #   servlet:
    #     context-path: /
    #     session:
    #       timeout: 3600
    #   port: 8080
    # logging:
    #   level:
    #     root: INFO
    #     jdbc:
    #       audit: INFO
    #       resultset: INFO
    #       resultsettable: INFO #SQL 결과 데이터 Table을 로그로 남긴다. #TODO:서버 환경별로 제한 필요.
    #       sqlonly: INFO #SQL만 로그로 남긴다.
    #       sqltiming: INFO #SQL과 소요시간을 표기한다. #TODO:서버 환경별로 제한 필요.
    #       connection: INFO # 커넥션 확인가능
    #   pattern:
    #     console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr([${spring.application.name},%X{trace_id},%X{span_id}]) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m %n%wEx"

    # pagehelper:
    #   helper-dialect: postgresql

    # springdoc:
    #   default-consumes-media-type: application/json;charset=UTF-8
    #   default-produces-media-type: application/json;charset=UTF-8
    #   swagger-ui:
    #     path: /
    #     disable-swagger-default-url: true
    #     display-request-duration: true
    #     tags-sorter: alpha
    #     operations-sorter: alpha
    #     doc-expansion: none
    #     urlsPrimaryName: 전체

    # swagger:
    #   url: http://localhost:8080
    #   description: Local Server URL

    # environment:
    #   object-storage-accessKey: ncp_iam_BGASKRWxyxTJyKAVP7hQ
    #   object-storage-secretKey: ncp_iam_BGKSKRRAuwMMboFyLlmGnHo78sw1cIjeIZ
    #   object-storage-endPoint: https://kr.object.gov-ncloudstorage.com
    #   object-storage-bucket: dev-mossp-files-bucket
    #   object-storage-goodsimg-bucket: mossp-dev-product-bucket
    #   object-storage-regionName: gov-standard
    #   object-storage-rootDir: mossp
    #   object-storage-options-date-suffix:

    # # Redis Stream
    # stream:
    #   # test-prefix: HSH
    #   stream-max-length: 1000
    #   test-prefix: null
    #   prefix: MOSSP_STREAM
    #   consumer:
    #     group:
    #       cips: CIPS
    #       smdc: SMDC
    #       scm: SCM

    # #external api
    # external:
    #   api:
    #     scm:
    #       token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEyMzQ1Njc4OTAiLCJuYW1lIjoiSm9obiBEb2UiLCJpYXQiOjE1MTYyMzkwMjJ9.Wp55KRKfBmD9oafN8DRB0g0CWp7baHpij2stsEz5Gzw
    #       url: http://localhost:9090
    #       send-telno: "01000000000"
    #     ess:
    #       token:
    #       url: https://deva.mossp.co.kr
    #     cips:
    #       token:
    #       url: https://devb.mossp.co.kr
    #     rms:
    #       token: aaa
    #       url: https://devrms.gosuper.kr
    #     cosmo:
    #       url: https://devcoreuse3.cosmo.or.kr:20443/api/recvJsonData.do

    # ---
    # #mega-bird message
    # mega-bird:
    #   token: aaa
    # barobill:
    #   cert-key: aaa

    # ---
    # # actuator, Prometheus
    # management:
    #   endpoints:
    #     web:
    #       exposure:
    #         include: health, info, metrics, prometheus
    #   # (확인필요) management.endpoint.health.show-details: 서킷 브레이커 Status를 Spring Actuator에서 보기위함
    #   # https://seongwon.dev/MSA/20230428-Resilience4J%EB%A1%9C_SpringBoot%EC%97%90%EC%84%9C_CircuitBreaker_%EC%82%AC%EC%9A%A9%ED%95%B4%EB%B3%B4%EA%B8%B0/
    #   endpoint:
    #     health:
    #       show-details: always
    #   health:
    #     # (확인필요) management.health.circuitbreakers.enabled: 서킷 브레이커 Status를 Spring Actuator에서 보기위함
    #     # https://seongwon.dev/MSA/20230428-Resilience4J%EB%A1%9C_SpringBoot%EC%97%90%EC%84%9C_CircuitBreaker_%EC%82%AC%EC%9A%A9%ED%95%B4%EB%B3%B4%EA%B8%B0/
    #     circuitbreakers:
    #       enabled: true
    #     probes:
    #       enabled: true
    #   metrics:
    #     distribution:
    #       percentiles-histogram:
    #         http.server.requests: true
    #       minimum-expected-value:
    #         http.server.requests: 5ms
    #       maximum-expected-value:
    #         http.server.requests: 1000ms

    # otel:
    #   propagators:
    #     - tracecontext
    #     - baggage
    #   resource:
    #     attributes:
    #       environment: local
    #       app: api-smdc
    #   traces:
    #     exporter: logging
    #   metrics:
    #     exporter: none
    #   logs:
    #     exporter: none
    #   instrumentation:
    #     logback-appender:
    #       enabled: true
    #       experimental-log-attributes: true
    #       experimental:
    #         capture-mdc-attributes:
    #           - "*"
    #         capture-marker-attribute: true
    #         capture-logger-context-attributes: true
    #         capture-key-value-pair-attributes: true
    #         capture-code-attributes: true
    # ---
    # megabird-sms:
    #   host-url: https://api.megabird.co.kr:8080
    #   send-service-url: /v1/openapi/sms/send
    #   upload-service-url: /v1/openapi/common/file/upload
    #   auth-token: aaaa
    # #  공공데이터
    # odcloud-open-data:
    #   url: https://api.odcloud.kr/api
    #   encodingServiceKey:
    #   decodingServiceKey:
    # #
    # r-open-feign:
    #   url: http://api.mossp.svc:8080
    #   api-statsPubPerRptMng: /response-management
    #   api-statsPubPerRqstMng: /response-management
    #   api-statsPubRptMng: /response-management
    #   api-statsPubRqstMng: /response-management
    # #
    # a-open-feign:
    #   url: https://dev4.mossp.co.kr
    #   token: aaaa
    # b-open-feign:
    #   url: https://dev3.mossp.co.kr
    #   token: aaaa
    # # site
    # c-open-feign:
    #   url: https://dev2.mossp.co.kr
    #   token: aaaa
    # # site
    # d-open-feign:
    #   url: https://dev1.mossp.co.kr
    #   token: aaaa

    # feign:
    #   client:
    #     config:
    #       default:
    #         connectTimeout: 3000
    #         readTimeout: 3000
    #         loggerLevel: FULL
    # # 데이터스트림즈(DS)

    # # resilience4j: circuit-breaker 상태관리
    # # https://seongwon.dev/MSA/20230428-Resilience4J%EB%A1%9C_SpringBoot%EC%97%90%EC%84%9C_CircuitBreaker_%EC%82%AC%EC%9A%A9%ED%95%B4%EB%B3%B4%EA%B8%B0/
    # resilience4j:
    #   circuitbreaker:
    #     # instances: circuitbreaker를 적용할 인스턴스를 지정
    #     instances:
    #       # member-breaker: 임의의 인스턴스 이름을 지정
    #       member-breaker:
    #         registerHealthIndicator: true
    #         automaticTransitionFromOpenToHalfOpenEnabled: true # OPEN에서 HALF OPEN으로 자동 변환 여부 설정
    #         failureRateThreshold: 50 # 실패율 임계값
    #         minimumNumberOfCalls: 5 # 실패율 또는 느린 호출율을 계산하기에 필요한 최소 호출 수
    #         permittedNumberOfCallsInHalfOpenState: 3 # HALF OPEN상태에서 허용할 요청 수
    #         slidingWindowSize: 10 # 슬라이딩 윈도우의 크기
    #         waitDurationInOpenState: 5000 # OPEN에서 HALF OPEN으로 변하기 까지 걸리는 시간
    #         slidingWindowType: COUNT_BASED # 호출 결과를 기록할 슬라이딩 윈도우의 타입 설정
    #         recordExceptions:
    #           - feign.FeignException
