apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-spass
  namespace: spass
  labels:
    app.kubernetes.io/name: api-spass
spec:
  replicas: 4
  selector:
    matchLabels:
      app.kubernetes.io/name: api-spass
  template:
    metadata:
      labels:
        app.kubernetes.io/name: api-spass
    spec:
      serviceAccountName: api-spass
      containers:
        - name: api-spass
          image: mossp-prod-container-registry.ncr.gov-ntruss.com/api-spass:61
          imagePullPolicy: IfNotPresent
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
          resources:
            requests:
              cpu: 100m
              memory: 1000Mi
            limits:
              cpu: 1000m
              memory: 2000Mi
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: actuator
              containerPort: 8081
              protocol: TCP
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: actuator
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: actuator
            initialDelaySeconds: 30
            periodSeconds: 60
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: actuator
            periodSeconds: 30
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 10
          volumeMounts:
            - mountPath: /config
              name: spass-config
      nodeSelector:
        role: spass
      volumes:
        - name: spass-config
          configMap:
            name: spass-config
      imagePullSecrets:
        - name: cr-credential
