apiVersion: v1
kind: Service
metadata:
  name: api-sample
  namespace: mossp
  labels:
    app.kubernetes.io/name: api-sample
  annotations:
    boot.spring.io/actuator: http://:8081/actuator
    alb.ingress.kubernetes.io/healthcheck-path: /actuator/health/readiness
    alb.ingress.kubernetes.io/healthcheck-port: '30321'    
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30322
    - name: actuator
      port: 8081
      protocol: TCP
      targetPort: 8081
      nodePort: 30321     
  selector:
    app.kubernetes.io/name: api-sample
  sessionAffinity: None