apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: api-spass
  namespace: default
  labels:
    app.kubernetes.io/name: api-spass
rules:
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ""
    resources:
      - secrets
      - configmaps
