apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: api-sample
  namespace: mossp
  labels:
    app.kubernetes.io/name: api-sample
rules:
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - secrets
      - configmaps
